version: "2"
linters:
  disable-all: true
  enable:
    - errcheck
    - gocognit
    - gocritic
    - gocyclo
    - misspell
    - staticcheck
    - whitespace
formatters:
  disable-all: true
  enable:
    - gofmt
    - goimports
