services:
  api:
    container_name: blog-backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      BLOG_ENV: dev
      BLOG_APP_PORT: 3000
      BLOG_LOG_LEVEL: debug
      BLOG_AWS_S3_BUCKET: ${BLOG_AWS_S3_BUCKET:?err}
      BLOG_AWS_S3_THUMBNAIL_DIRECTORY: ${BLOG_AWS_S3_THUMBNAIL_DIRECTORY:?err}
      BLOG_AWS_S3_CONTENT_IMAGE_DIRECTORY: ${BLOG_AWS_S3_CONTENT_IMAGE_DIRECTORY:?err}
      BLOG_AWS_S3_AVATAR_IMAGE_DIRECTORY: ${BLOG_AWS_S3_AVATAR_IMAGE_DIRECTORY:?err}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?err}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?err}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:?err}
      ADMIN_NAME: ${ADMIN_EMAIL?err}
      ADMIN_EMAIL: ${ADMIN_EMAIL?err}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD?err}
      JWT_SECRET: ${JWT_SECRET?err}
      BLOG_KVS_HOST: ${BLOG_KVS_HOST:-blog-kvs}
      BLOG_KVS_PORT: ${BLOG_KVS_PORT:-6379}
      BLOG_KVS_USER: ${BLOG_KVS_USER:-default}
      BLOG_KVS_PASS: ${BLOG_KVS_PASS:-redispw}
      BLOG_KVS_TLS_ENABLED: ${BLOG_KVS_TLS_ENABLED:-false}
      BLOG_DB_HOST: ${BLOG_DB_HOST:-blog-db-pg}
      BLOG_DB_PORT: ${BLOG_DB_PORT:-5432}
      BLOG_DB_USER: ${BLOG_DB_USER:-blog}
      BLOG_DB_PASS: ${BLOG_DB_PASS:-blog}
      BLOG_DB_NAME: ${BLOG_DB_NAME:-blog}
      BLOG_DB_TLS_ENABLED: ${BLOG_KVS_TLS_ENABLED:-false}
      BLOG_DB_SSL_MODE: ${BLOG_DB_SSL_MODE:-disable}
      CORS_WHITE_LIST: ${CORS_WHITE_LIST}
      CDN_DOMAIN: ${CDN_DOMAIN}
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN:?err}
    depends_on:
      - blog-db-pg
      - blog-db-pg-test
      - blog-kvs

  blog-db-pg:
    image: postgres:latest
    container_name: blog-db-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog
    volumes:
      - blog-db-pg-data:/var/lib/postgresql/data

  blog-db-pg-test:
    image: postgres:latest
    container_name: blog-db-pg-test
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog
    volumes:
      - blog-db-pg-test-data:/var/lib/postgresql/data

  blog-kvs:
    image: redis:latest
    container_name: blog-redis
    ports:
      - "6379:6379"
    volumes:
      - blog-redis-data:/data

volumes:
  blog-db-pg-data:
  blog-db-pg-test-data:
  blog-redis-data:
