
-- +migrate Up
CREATE TABLE IF NOT EXISTS blogs (
  id          SERIAL NOT NULL PRIMARY KEY,
  author_id   INT NOT NULL,
  title       TEXT NOT NULL,
  content     TEXT NOT NULL,
  description TEXT NOT NULL,
  thumbnail_image_file_name TEXT,
  is_public   BOOLEAN NOT NULL DEFAULT FALSE,
  created BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
  modified BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS tags (
  id          SERIAL NOT NULL PRIMARY KEY,
  name        VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS blogs_tags (
  id          SERIAL NOT NULL PRIMARY KEY,
  blog_id     INT NOT NULL,
  tag_id      INT NOT NULL,
  UNIQUE(blog_id, tag_id)
);

CREATE TABLE IF NOT EXISTS users (
  id          SERIAL NOT NULL PRIMARY KEY,
  name        TEXT NOT NULL,
  email       VARCHAR(255) NOT NULL UNIQUE,
  password    TEXT NOT NULL,
  created BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
  modified BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)
);

-- +migrate Down
DROP TABLE IF EXISTS blogs;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS blogs_tags;
DROP TABLE IF EXISTS users;
