name: Test and deployment

on: push

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=./.golangci.yml ./..."
          fail_level: warning
          reporter: "github-pr-review"

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    env:
      BLOG_ENV: ${{ secrets.BLOG_ENV }}
      BLOG_APP_PORT: ${{ secrets.BLOG_APP_PORT }}
      BLOG_AWS_S3_BUCKET: ${{ secrets.BLOG_AWS_S3_BUCKET }}
      BLOG_AWS_S3_THUMBNAIL_DIRECTORY: ${{ secrets.BLOG_AWS_S3_THUMBNAIL_DIRECTORY }}
      BLOG_AWS_S3_CONTENT_IMAGE_DIRECTORY: ${{ secrets.BLOG_AWS_S3_CONTENT_IMAGE_DIRECTORY }}
      ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      BLOG_DB_HOST: 127.0.0.1
      BLOG_DB_PORT: 33061
      BLOG_DB_USER: blog
      BLOG_DB_PASS: blog
      BLOG_DB_NAME: blog
      BLOG_DB_TLS_ENABLED: false
      BLOG_KVS_HOST: localhost
      BLOG_KVS_PORT: 6379
      BLOG_KVS_USER: default
      BLOG_KVS_PASS: redispw
      BLOG_KVS_TLS_ENABLED: false
      OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    services:
      postgresql:
        image: postgres:latest
        ports:
          - "54321:5432"
        env:
          POSTGRES_USER: blog
          POSTGRES_PASSWORD: blog
          POSTGRES_DB: blog
        options: >-
          --health-cmd "PGPASSWORD=blog psql -h 127.0.0.1 -p 5432 -U blog -d blog -c 'SELECT 1'"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli -h localhost ping"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 6379:6379

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"
          cache: false
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          mask-aws-account-id: true
      - run: go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v1

  deploy-development:
    runs-on: ubuntu-latest
    needs: [golangci-lint, test]
    if: ${{ startsWith(github.ref, 'refs/heads/feature') }}
    timeout-minutes: 30
    environment:
      name: development
    permissions:
      id-token: write
    env:
      OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_DEPLOY_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true
      - name: deploy development
        run: cd cdk && npm install && npm run deploy

  deploy-production:
    runs-on: ubuntu-latest
    needs: [golangci-lint, test]
    if: ${{ github.ref == 'refs/heads/master' }}
    timeout-minutes: 30
    environment:
      name: production
    permissions:
      id-token: write
    env:
      OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_DEPLOY_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true
      - name: deploy
        run: cd cdk && npm install && npm run deploy:prod
